name : moxy_app
services :
    app:
      build :
        context : .
        dockerfile : Dockerfile.dev
      restart : always
      volumes : 
        - ./app:/usr/src/app/
      ports:
        - 8060:8060

    